# Created by shenping at 2020/4/23
Feature: 获取找货基本信息接口测试用例


  Scenario: [0]获取找货基本信息
    * 请求"query_hunt_treasure_basic_info_url"接口，查询
    """
      {'link_url':'',
        'http_method': 'get',
        'evn':'CI_ENV',
         'url_params':{
         }
      }
    """
    * 接口返回码"200"
    * 验证接口返回值
    """
      {
          "cacheType": "",
          "code": 0,
          "data": {
              "braceletCircleList": [{
                  "circleValue": "52~53毫米",
                  "id": 1
              }, {
                  "circleValue": "53~54毫米",
                  "id": 2
              }, {
                  "circleValue": "54~55毫米",
                  "id": 3
              }, {
                  "circleValue": "55~56毫米",
                  "id": 4
              }, {
                  "circleValue": "56~57毫米",
                  "id": 5
              }, {
                  "circleValue": "57~58毫米",
                  "id": 6
              }, {
                  "circleValue": "58~59毫米",
                  "id": 7
              }, {
                  "circleValue": "59~60毫米",
                  "id": 8
              }, {
                  "circleValue": "60毫米以上",
                  "id": 9
              }],
              "budgetRangeList": [{
                  "id": 1,
                  "rangeValue": "3千~1万"
              }, {
                  "id": 2,
                  "rangeValue": "1万~2万"
              }, {
                  "id": 3,
                  "rangeValue": "2万~5万"
              }, {
                  "id": 4,
                  "rangeValue": "5万~10万"
              }, {
                  "id": 5,
                  "rangeValue": "10万~20万"
              }, {
                  "id": 6,
                  "rangeValue": "20万以上"
              }],
              "labelCategoryList": [{
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic-renqun-01.png",
                  "categoryName": "适用人群",
                  "id": 1,
                  "labelList": [{
                      "categoryId": 1,
                      "id": 1,
                      "labelImgUrl": "",
                      "labelName": "男士"
                  }, {
                      "categoryId": 1,
                      "id": 2,
                      "labelImgUrl": "",
                      "labelName": "女士"
                  }, {
                      "categoryId": 1,
                      "id": 3,
                      "labelImgUrl": "",
                      "labelName": "孩子"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_yongtu.png",
                  "categoryName": "用途",
                  "id": 2,
                  "labelList": [{
                      "categoryId": 2,
                      "id": 4,
                      "labelImgUrl": "",
                      "labelName": "传家"
                  }, {
                      "categoryId": 2,
                      "id": 5,
                      "labelImgUrl": "",
                      "labelName": "送人"
                  }, {
                      "categoryId": 2,
                      "id": 6,
                      "labelImgUrl": "",
                      "labelName": "自戴"
                  }, {
                      "categoryId": 2,
                      "id": 7,
                      "labelImgUrl": "",
                      "labelName": "收藏"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_caizhi.png",
                  "categoryName": "材质",
                  "id": 3,
                  "labelList": [{
                      "categoryId": 3,
                      "id": 8,
                      "labelImgUrl": "",
                      "labelName": "翡翠"
                  }, {
                      "categoryId": 3,
                      "id": 9,
                      "labelImgUrl": "",
                      "labelName": "和田玉"
                  }, {
                      "categoryId": 3,
                      "id": 10,
                      "labelImgUrl": "",
                      "labelName": "彩宝"
                  }, {
                      "categoryId": 3,
                      "id": 11,
                      "labelImgUrl": "",
                      "labelName": "琥珀/蜜蜡"
                  }, {
                      "categoryId": 3,
                      "id": 12,
                      "labelImgUrl": "",
                      "labelName": "南红"
                  }, {
                      "categoryId": 3,
                      "id": 13,
                      "labelImgUrl": "",
                      "labelName": "珍珠"
                  }, {
                      "categoryId": 3,
                      "id": 14,
                      "labelImgUrl": "",
                      "labelName": "墨翠"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_gongyi-01.png",
                  "categoryName": "工艺",
                  "id": 4,
                  "labelList": [{
                      "categoryId": 4,
                      "id": 15,
                      "labelImgUrl": "",
                      "labelName": "豪镶"
                  }, {
                      "categoryId": 4,
                      "id": 16,
                      "labelImgUrl": "",
                      "labelName": "金镶"
                  }, {
                      "categoryId": 4,
                      "id": 17,
                      "labelImgUrl": "",
                      "labelName": "素身"
                  }, {
                      "categoryId": 4,
                      "id": 18,
                      "labelImgUrl": "",
                      "labelName": "设计款"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_yanse.png",
                  "categoryName": "颜色",
                  "id": 5,
                  "labelList": [{
                      "categoryId": 5,
                      "id": 19,
                      "labelImgUrl": "",
                      "labelName": "满绿"
                  }, {
                      "categoryId": 5,
                      "id": 20,
                      "labelImgUrl": "",
                      "labelName": "阳绿"
                  }, {
                      "categoryId": 5,
                      "id": 21,
                      "labelImgUrl": "",
                      "labelName": "紫色"
                  }, {
                      "categoryId": 5,
                      "id": 22,
                      "labelImgUrl": "",
                      "labelName": "飘花"
                  }, {
                      "categoryId": 5,
                      "id": 23,
                      "labelImgUrl": "",
                      "labelName": "红黄翡"
                  }, {
                      "categoryId": 5,
                      "id": 24,
                      "labelImgUrl": "",
                      "labelName": "春带彩"
                  }, {
                      "categoryId": 5,
                      "id": 25,
                      "labelImgUrl": "",
                      "labelName": "黄加绿"
                  }, {
                      "categoryId": 5,
                      "id": 26,
                      "labelImgUrl": "",
                      "labelName": "三彩"
                  }, {
                      "categoryId": 5,
                      "id": 27,
                      "labelImgUrl": "",
                      "labelName": "冰冰透透"
                  }, {
                      "categoryId": 5,
                      "id": 28,
                      "labelImgUrl": "",
                      "labelName": "胶感"
                  }, {
                      "categoryId": 5,
                      "id": 29,
                      "labelImgUrl": "",
                      "labelName": "无色"
                  }, {
                      "categoryId": 5,
                      "id": 30,
                      "labelImgUrl": "",
                      "labelName": "带点绿"
                  }]
              }],
              "styleCategoryList": [{
                  "categoryImgUrl": "",
                  "categoryName": "手镯",
                  "id": 1,
                  "styleList": [{
                      "categoryId": "1",
                      "id": 1,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-01.png",
                      "styleName": "圆条镯"
                  }, {
                      "categoryId": "1",
                      "id": 2,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-02.png",
                      "styleName": "扁条镯"
                  }, {
                      "categoryId": "1",
                      "id": 3,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-03.png",
                      "styleName": "贵妃镯"
                  }, {
                      "categoryId": "1",
                      "id": 4,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-04.png",
                      "styleName": "异性镯"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "挂件",
                  "id": 2,
                  "styleList": [{
                      "categoryId": "2",
                      "id": 5,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-01.png",
                      "styleName": "佛"
                  }, {
                      "categoryId": "2",
                      "id": 6,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-02.png",
                      "styleName": "观音"
                  }, {
                      "categoryId": "2",
                      "id": 7,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-03.png",
                      "styleName": "叶子"
                  }, {
                      "categoryId": "2",
                      "id": 8,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-04.png",
                      "styleName": "如意"
                  }, {
                      "categoryId": "2",
                      "id": 9,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-05.png",
                      "styleName": "平安扣"
                  }, {
                      "categoryId": "2",
                      "id": 10,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-06.png",
                      "styleName": "路路通"
                  }, {
                      "categoryId": "2",
                      "id": 11,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-07.png",
                      "styleName": "福豆"
                  }, {
                      "categoryId": "2",
                      "id": 12,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-08.png",
                      "styleName": "福瓜"
                  }, {
                      "categoryId": "2",
                      "id": 13,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-09.png",
                      "styleName": "葫芦"
                  }, {
                      "categoryId": "2",
                      "id": 14,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-10.png",
                      "styleName": "瑞兽"
                  }, {
                      "categoryId": "2",
                      "id": 15,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-11.png",
                      "styleName": "牌子"
                  }, {
                      "categoryId": "2",
                      "id": 16,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-12.png",
                      "styleName": "生肖"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "首饰",
                  "id": 3,
                  "styleList": [{
                      "categoryId": "3",
                      "id": 17,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-01.png",
                      "styleName": "耳线"
                  }, {
                      "categoryId": "3",
                      "id": 18,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-02.png",
                      "styleName": "耳钉"
                  }, {
                      "categoryId": "3",
                      "id": 19,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-03.png",
                      "styleName": "耳坠"
                  }, {
                      "categoryId": "3",
                      "id": 20,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-04.png",
                      "styleName": "手链"
                  }, {
                      "categoryId": "3",
                      "id": 21,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-05.png",
                      "styleName": "戒指"
                  }, {
                      "categoryId": "3",
                      "id": 22,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-06.png",
                      "styleName": "胸针"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "珠串",
                  "id": 4,
                  "styleList": [{
                      "categoryId": "4",
                      "id": 23,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zhuchuan-01.png",
                      "styleName": "手串 "
                  }, {
                      "categoryId": "4",
                      "id": 24,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zhuchuan-02.png",
                      "styleName": "手链"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "戒面裸石",
                  "id": 5,
                  "styleList": [{
                      "categoryId": "5",
                      "id": 25,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-01.png",
                      "styleName": "圆形"
                  }, {
                      "categoryId": "5",
                      "id": 26,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-02.png",
                      "styleName": "椭圆形"
                  }, {
                      "categoryId": "5",
                      "id": 27,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-03.png",
                      "styleName": "马鞍"
                  }, {
                      "categoryId": "5",
                      "id": 28,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-04.png",
                      "styleName": "水滴形"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "杂类",
                  "id": 6,
                  "styleList": [{
                      "categoryId": "6",
                      "id": 29,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-01.png",
                      "styleName": "手玩件"
                  }, {
                      "categoryId": "6",
                      "id": 30,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-02.png",
                      "styleName": "车包挂"
                  }, {
                      "categoryId": "6",
                      "id": 31,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-03.png",
                      "styleName": "印章"
                  }, {
                      "categoryId": "6",
                      "id": 32,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-04.png",
                      "styleName": "摆件"
                  }]
              }]
          },
          "displayAlert": false,
          "displayTip": false,
          "hashData": "",
          "info": {
              "braceletCircleList": [{
                  "circleValue": "52~53毫米",
                  "id": 1
              }, {
                  "circleValue": "53~54毫米",
                  "id": 2
              }, {
                  "circleValue": "54~55毫米",
                  "id": 3
              }, {
                  "circleValue": "55~56毫米",
                  "id": 4
              }, {
                  "circleValue": "56~57毫米",
                  "id": 5
              }, {
                  "circleValue": "57~58毫米",
                  "id": 6
              }, {
                  "circleValue": "58~59毫米",
                  "id": 7
              }, {
                  "circleValue": "59~60毫米",
                  "id": 8
              }, {
                  "circleValue": "60毫米以上",
                  "id": 9
              }],
              "budgetRangeList": [{
                  "id": 1,
                  "rangeValue": "3千~1万"
              }, {
                  "id": 2,
                  "rangeValue": "1万~2万"
              }, {
                  "id": 3,
                  "rangeValue": "2万~5万"
              }, {
                  "id": 4,
                  "rangeValue": "5万~10万"
              }, {
                  "id": 5,
                  "rangeValue": "10万~20万"
              }, {
                  "id": 6,
                  "rangeValue": "20万以上"
              }],
              "labelCategoryList": [{
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic-renqun-01.png",
                  "categoryName": "适用人群",
                  "id": 1,
                  "labelList": [{
                      "categoryId": 1,
                      "id": 1,
                      "labelImgUrl": "",
                      "labelName": "男士"
                  }, {
                      "categoryId": 1,
                      "id": 2,
                      "labelImgUrl": "",
                      "labelName": "女士"
                  }, {
                      "categoryId": 1,
                      "id": 3,
                      "labelImgUrl": "",
                      "labelName": "孩子"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_yongtu.png",
                  "categoryName": "用途",
                  "id": 2,
                  "labelList": [{
                      "categoryId": 2,
                      "id": 4,
                      "labelImgUrl": "",
                      "labelName": "传家"
                  }, {
                      "categoryId": 2,
                      "id": 5,
                      "labelImgUrl": "",
                      "labelName": "送人"
                  }, {
                      "categoryId": 2,
                      "id": 6,
                      "labelImgUrl": "",
                      "labelName": "自戴"
                  }, {
                      "categoryId": 2,
                      "id": 7,
                      "labelImgUrl": "",
                      "labelName": "收藏"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_caizhi.png",
                  "categoryName": "材质",
                  "id": 3,
                  "labelList": [{
                      "categoryId": 3,
                      "id": 8,
                      "labelImgUrl": "",
                      "labelName": "翡翠"
                  }, {
                      "categoryId": 3,
                      "id": 9,
                      "labelImgUrl": "",
                      "labelName": "和田玉"
                  }, {
                      "categoryId": 3,
                      "id": 10,
                      "labelImgUrl": "",
                      "labelName": "彩宝"
                  }, {
                      "categoryId": 3,
                      "id": 11,
                      "labelImgUrl": "",
                      "labelName": "琥珀/蜜蜡"
                  }, {
                      "categoryId": 3,
                      "id": 12,
                      "labelImgUrl": "",
                      "labelName": "南红"
                  }, {
                      "categoryId": 3,
                      "id": 13,
                      "labelImgUrl": "",
                      "labelName": "珍珠"
                  }, {
                      "categoryId": 3,
                      "id": 14,
                      "labelImgUrl": "",
                      "labelName": "墨翠"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_gongyi-01.png",
                  "categoryName": "工艺",
                  "id": 4,
                  "labelList": [{
                      "categoryId": 4,
                      "id": 15,
                      "labelImgUrl": "",
                      "labelName": "豪镶"
                  }, {
                      "categoryId": 4,
                      "id": 16,
                      "labelImgUrl": "",
                      "labelName": "金镶"
                  }, {
                      "categoryId": 4,
                      "id": 17,
                      "labelImgUrl": "",
                      "labelName": "素身"
                  }, {
                      "categoryId": 4,
                      "id": 18,
                      "labelImgUrl": "",
                      "labelName": "设计款"
                  }]
              }, {
                  "categoryImgUrl": "https://res.jaadee.net/app/findgoods/label/ic_yanse.png",
                  "categoryName": "颜色",
                  "id": 5,
                  "labelList": [{
                      "categoryId": 5,
                      "id": 19,
                      "labelImgUrl": "",
                      "labelName": "满绿"
                  }, {
                      "categoryId": 5,
                      "id": 20,
                      "labelImgUrl": "",
                      "labelName": "阳绿"
                  }, {
                      "categoryId": 5,
                      "id": 21,
                      "labelImgUrl": "",
                      "labelName": "紫色"
                  }, {
                      "categoryId": 5,
                      "id": 22,
                      "labelImgUrl": "",
                      "labelName": "飘花"
                  }, {
                      "categoryId": 5,
                      "id": 23,
                      "labelImgUrl": "",
                      "labelName": "红黄翡"
                  }, {
                      "categoryId": 5,
                      "id": 24,
                      "labelImgUrl": "",
                      "labelName": "春带彩"
                  }, {
                      "categoryId": 5,
                      "id": 25,
                      "labelImgUrl": "",
                      "labelName": "黄加绿"
                  }, {
                      "categoryId": 5,
                      "id": 26,
                      "labelImgUrl": "",
                      "labelName": "三彩"
                  }, {
                      "categoryId": 5,
                      "id": 27,
                      "labelImgUrl": "",
                      "labelName": "冰冰透透"
                  }, {
                      "categoryId": 5,
                      "id": 28,
                      "labelImgUrl": "",
                      "labelName": "胶感"
                  }, {
                      "categoryId": 5,
                      "id": 29,
                      "labelImgUrl": "",
                      "labelName": "无色"
                  }, {
                      "categoryId": 5,
                      "id": 30,
                      "labelImgUrl": "",
                      "labelName": "带点绿"
                  }]
              }],
              "styleCategoryList": [{
                  "categoryImgUrl": "",
                  "categoryName": "手镯",
                  "id": 1,
                  "styleList": [{
                      "categoryId": "1",
                      "id": 1,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-01.png",
                      "styleName": "圆条镯"
                  }, {
                      "categoryId": "1",
                      "id": 2,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-02.png",
                      "styleName": "扁条镯"
                  }, {
                      "categoryId": "1",
                      "id": 3,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-03.png",
                      "styleName": "贵妃镯"
                  }, {
                      "categoryId": "1",
                      "id": 4,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shouzhuo-04.png",
                      "styleName": "异性镯"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "挂件",
                  "id": 2,
                  "styleList": [{
                      "categoryId": "2",
                      "id": 5,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-01.png",
                      "styleName": "佛"
                  }, {
                      "categoryId": "2",
                      "id": 6,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-02.png",
                      "styleName": "观音"
                  }, {
                      "categoryId": "2",
                      "id": 7,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-03.png",
                      "styleName": "叶子"
                  }, {
                      "categoryId": "2",
                      "id": 8,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-04.png",
                      "styleName": "如意"
                  }, {
                      "categoryId": "2",
                      "id": 9,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-05.png",
                      "styleName": "平安扣"
                  }, {
                      "categoryId": "2",
                      "id": 10,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-06.png",
                      "styleName": "路路通"
                  }, {
                      "categoryId": "2",
                      "id": 11,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-07.png",
                      "styleName": "福豆"
                  }, {
                      "categoryId": "2",
                      "id": 12,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-08.png",
                      "styleName": "福瓜"
                  }, {
                      "categoryId": "2",
                      "id": 13,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-09.png",
                      "styleName": "葫芦"
                  }, {
                      "categoryId": "2",
                      "id": 14,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-10.png",
                      "styleName": "瑞兽"
                  }, {
                      "categoryId": "2",
                      "id": 15,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-11.png",
                      "styleName": "牌子"
                  }, {
                      "categoryId": "2",
                      "id": 16,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-guajian-12.png",
                      "styleName": "生肖"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "首饰",
                  "id": 3,
                  "styleList": [{
                      "categoryId": "3",
                      "id": 17,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-01.png",
                      "styleName": "耳线"
                  }, {
                      "categoryId": "3",
                      "id": 18,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-02.png",
                      "styleName": "耳钉"
                  }, {
                      "categoryId": "3",
                      "id": 19,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-03.png",
                      "styleName": "耳坠"
                  }, {
                      "categoryId": "3",
                      "id": 20,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-04.png",
                      "styleName": "手链"
                  }, {
                      "categoryId": "3",
                      "id": 21,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-05.png",
                      "styleName": "戒指"
                  }, {
                      "categoryId": "3",
                      "id": 22,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-shoushi-06.png",
                      "styleName": "胸针"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "珠串",
                  "id": 4,
                  "styleList": [{
                      "categoryId": "4",
                      "id": 23,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zhuchuan-01.png",
                      "styleName": "手串 "
                  }, {
                      "categoryId": "4",
                      "id": 24,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zhuchuan-02.png",
                      "styleName": "手链"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "戒面裸石",
                  "id": 5,
                  "styleList": [{
                      "categoryId": "5",
                      "id": 25,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-01.png",
                      "styleName": "圆形"
                  }, {
                      "categoryId": "5",
                      "id": 26,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-02.png",
                      "styleName": "椭圆形"
                  }, {
                      "categoryId": "5",
                      "id": 27,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-03.png",
                      "styleName": "马鞍"
                  }, {
                      "categoryId": "5",
                      "id": 28,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-jiemian-04.png",
                      "styleName": "水滴形"
                  }]
              }, {
                  "categoryImgUrl": "",
                  "categoryName": "杂类",
                  "id": 6,
                  "styleList": [{
                      "categoryId": "6",
                      "id": 29,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-01.png",
                      "styleName": "手玩件"
                  }, {
                      "categoryId": "6",
                      "id": 30,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-02.png",
                      "styleName": "车包挂"
                  }, {
                      "categoryId": "6",
                      "id": 31,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-03.png",
                      "styleName": "印章"
                  }, {
                      "categoryId": "6",
                      "id": 32,
                      "styleImgUrl": "https://res.jaadee.net/app/findgoods/style/ic-zalei-04.png",
                      "styleName": "摆件"
                  }]
              }]
          },
          "message": "获取找货基础信息成功",
          "msg": "获取找货基础信息成功",
          "status": 0
      }
    """