# Created by shenping at 2020/4/8
Feature: 获取商品过滤种类接口测试用例

  Scenario: [0]获取种类
    * 请求"query_goods_filter_url"接口，获取种类
    """
      {'link_url':'',
        'http_method': 'post',
        'evn':'CI_NEWAPI',
         'url_params':{
              "platId": 1,
              "catId": "19"
          }
      }
    """
    * 接口返回码"200"
    * 验证接口返回值
    """
      {
            "status": 0,
            "msg": "返回数据成功",
            "info": [{
                "text": "种",
                "sub": [{
                    "text": "所有种类",
                    "type": "transparentid",
                    "value": "0"
                }, {
                    "text": "玻璃种",
                    "type": "transparentid",
                    "value": "13"
                }, {
                    "text": "冰玻种",
                    "type": "transparentid",
                    "value": "14"
                }, {
                    "text": "冰种",
                    "type": "transparentid",
                    "value": "15"
                }, {
                    "text": "糯冰种",
                    "type": "transparentid",
                    "value": "16"
                }, {
                    "text": "细糯种",
                    "type": "transparentid",
                    "value": "17"
                }]
            }, {
                "text": "色",
                "sub": [{
                    "text": "所有颜色",
                    "type": "colorid",
                    "value": "0"
                }, {
                    "text": "阳绿",
                    "type": "colorid",
                    "value": "2"
                }, {
                    "text": "浓绿",
                    "type": "colorid",
                    "value": "3"
                }, {
                    "text": "翠色",
                    "type": "colorid",
                    "value": "4"
                }, {
                    "text": "青色",
                    "type": "colorid",
                    "value": "5"
                }, {
                    "text": "晴水",
                    "type": "colorid",
                    "value": "6"
                }, {
                    "text": "飘花",
                    "type": "colorid",
                    "value": "7"
                }, {
                    "text": "紫罗兰",
                    "type": "colorid",
                    "value": "8"
                }, {
                    "text": "红黄翡",
                    "type": "colorid",
                    "value": "9"
                }, {
                    "text": "多彩",
                    "type": "colorid",
                    "value": "10"
                }, {
                    "text": "墨翠",
                    "type": "colorid",
                    "value": "11"
                }, {
                    "text": "苹果绿",
                    "type": "colorid",
                    "value": "81"
                }, {
                    "text": "豆色",
                    "type": "colorid",
                    "value": "85"
                }, {
                    "text": "淡绿",
                    "type": "colorid",
                    "value": "79"
                }, {
                    "text": "满绿",
                    "type": "colorid",
                    "value": "80"
                }, {
                    "text": "帝王绿",
                    "type": "colorid",
                    "value": "83"
                }, {
                    "text": "蓝绿",
                    "type": "colorid",
                    "value": "84"
                }]
            }, {
                "text": "形状",
                "sub": [{
                    "text": "所有形状",
                    "type": "extid",
                    "value": ""
                }, {
                    "text": "圆条",
                    "type": "extid",
                    "value": "49"
                }, {
                    "text": "贵妃",
                    "type": "extid",
                    "value": "50"
                }, {
                    "text": "扁条",
                    "type": "extid",
                    "value": "51"
                }, {
                    "text": "方条",
                    "type": "extid",
                    "value": "52"
                }, {
                    "text": "个性",
                    "type": "extid",
                    "value": "53"
                }]
            }, {
                "text": "尺寸",
                "sub": [{
                    "text": "所有尺寸",
                    "type": "extid",
                    "value": "",
                    "checks": "1"
                }, {
                    "text": "52≤",
                    "type": "extid",
                    "value": "55",
                    "checks": "1"
                }, {
                    "text": "53mm",
                    "type": "extid",
                    "value": "56",
                    "checks": "1"
                }, {
                    "text": "54mm",
                    "type": "extid",
                    "value": "57",
                    "checks": "1"
                }, {
                    "text": "55mm",
                    "type": "extid",
                    "value": "58",
                    "checks": "1"
                }, {
                    "text": "56mm",
                    "type": "extid",
                    "value": "59",
                    "checks": "1"
                }, {
                    "text": "57mm",
                    "type": "extid",
                    "value": "60",
                    "checks": "1"
                }, {
                    "text": "58mm",
                    "type": "extid",
                    "value": "61",
                    "checks": "1"
                }, {
                    "text": "59mm",
                    "type": "extid",
                    "value": "62",
                    "checks": "1"
                }, {
                    "text": "≥60",
                    "type": "extid",
                    "value": "63",
                    "checks": "1"
                }]
            }, {
                "text": "价格",
                "sub": [{
                    "text": "所有价格",
                    "type": "pricewidth",
                    "value": "0-0"
                }, {
                    "text": "0-3千",
                    "type": "pricewidth",
                    "value": "1-3000"
                }, {
                    "text": "3千-8千",
                    "type": "pricewidth",
                    "value": "3000-8000"
                }, {
                    "text": "8千-1.5万",
                    "type": "pricewidth",
                    "value": "8000-15000"
                }, {
                    "text": "1.5万-3万",
                    "type": "pricewidth",
                    "value": "15000-30000"
                }, {
                    "text": "3万-5万",
                    "type": "pricewidth",
                    "value": "30000-50000"
                }, {
                    "text": "5万-10万",
                    "type": "pricewidth",
                    "value": "50000-100000"
                }, {
                    "text": "10万以上",
                    "type": "pricewidth",
                    "value": "100000-999999999"
                }]
            }],
            "hashData": "",
            "cacheType": "none",
            "code": 0,
            "message": "返回数据成功",
            "data": [{
                "text": "种",
                "sub": [{
                    "text": "所有种类",
                    "type": "transparentid",
                    "value": "0"
                }, {
                    "text": "玻璃种",
                    "type": "transparentid",
                    "value": "13"
                }, {
                    "text": "冰玻种",
                    "type": "transparentid",
                    "value": "14"
                }, {
                    "text": "冰种",
                    "type": "transparentid",
                    "value": "15"
                }, {
                    "text": "糯冰种",
                    "type": "transparentid",
                    "value": "16"
                }, {
                    "text": "细糯种",
                    "type": "transparentid",
                    "value": "17"
                }]
            }, {
                "text": "色",
                "sub": [{
                    "text": "所有颜色",
                    "type": "colorid",
                    "value": "0"
                }, {
                    "text": "阳绿",
                    "type": "colorid",
                    "value": "2"
                }, {
                    "text": "浓绿",
                    "type": "colorid",
                    "value": "3"
                }, {
                    "text": "翠色",
                    "type": "colorid",
                    "value": "4"
                }, {
                    "text": "青色",
                    "type": "colorid",
                    "value": "5"
                }, {
                    "text": "晴水",
                    "type": "colorid",
                    "value": "6"
                }, {
                    "text": "飘花",
                    "type": "colorid",
                    "value": "7"
                }, {
                    "text": "紫罗兰",
                    "type": "colorid",
                    "value": "8"
                }, {
                    "text": "红黄翡",
                    "type": "colorid",
                    "value": "9"
                }, {
                    "text": "多彩",
                    "type": "colorid",
                    "value": "10"
                }, {
                    "text": "墨翠",
                    "type": "colorid",
                    "value": "11"
                }, {
                    "text": "苹果绿",
                    "type": "colorid",
                    "value": "81"
                }, {
                    "text": "豆色",
                    "type": "colorid",
                    "value": "85"
                }, {
                    "text": "淡绿",
                    "type": "colorid",
                    "value": "79"
                }, {
                    "text": "满绿",
                    "type": "colorid",
                    "value": "80"
                }, {
                    "text": "帝王绿",
                    "type": "colorid",
                    "value": "83"
                }, {
                    "text": "蓝绿",
                    "type": "colorid",
                    "value": "84"
                }]
            }, {
                "text": "形状",
                "sub": [{
                    "text": "所有形状",
                    "type": "extid",
                    "value": ""
                }, {
                    "text": "圆条",
                    "type": "extid",
                    "value": "49"
                }, {
                    "text": "贵妃",
                    "type": "extid",
                    "value": "50"
                }, {
                    "text": "扁条",
                    "type": "extid",
                    "value": "51"
                }, {
                    "text": "方条",
                    "type": "extid",
                    "value": "52"
                }, {
                    "text": "个性",
                    "type": "extid",
                    "value": "53"
                }]
            }, {
                "text": "尺寸",
                "sub": [{
                    "text": "所有尺寸",
                    "type": "extid",
                    "value": "",
                    "checks": "1"
                }, {
                    "text": "52≤",
                    "type": "extid",
                    "value": "55",
                    "checks": "1"
                }, {
                    "text": "53mm",
                    "type": "extid",
                    "value": "56",
                    "checks": "1"
                }, {
                    "text": "54mm",
                    "type": "extid",
                    "value": "57",
                    "checks": "1"
                }, {
                    "text": "55mm",
                    "type": "extid",
                    "value": "58",
                    "checks": "1"
                }, {
                    "text": "56mm",
                    "type": "extid",
                    "value": "59",
                    "checks": "1"
                }, {
                    "text": "57mm",
                    "type": "extid",
                    "value": "60",
                    "checks": "1"
                }, {
                    "text": "58mm",
                    "type": "extid",
                    "value": "61",
                    "checks": "1"
                }, {
                    "text": "59mm",
                    "type": "extid",
                    "value": "62",
                    "checks": "1"
                }, {
                    "text": "≥60",
                    "type": "extid",
                    "value": "63",
                    "checks": "1"
                }]
            }, {
                "text": "价格",
                "sub": [{
                    "text": "所有价格",
                    "type": "pricewidth",
                    "value": "0-0"
                }, {
                    "text": "0-3千",
                    "type": "pricewidth",
                    "value": "1-3000"
                }, {
                    "text": "3千-8千",
                    "type": "pricewidth",
                    "value": "3000-8000"
                }, {
                    "text": "8千-1.5万",
                    "type": "pricewidth",
                    "value": "8000-15000"
                }, {
                    "text": "1.5万-3万",
                    "type": "pricewidth",
                    "value": "15000-30000"
                }, {
                    "text": "3万-5万",
                    "type": "pricewidth",
                    "value": "30000-50000"
                }, {
                    "text": "5万-10万",
                    "type": "pricewidth",
                    "value": "50000-100000"
                }, {
                    "text": "10万以上",
                    "type": "pricewidth",
                    "value": "100000-999999999"
                }]
            }]
        }
    """