# Created by shenping at 2020/4/8
Feature: 获取商品分类接口测试用例

  Scenario: [0]获取商品分类
    * 请求"query_goods_category_url"接口，获取分类
    """
      {'link_url':'',
        'http_method': 'post',
        'evn':'CI_NEWAPI',
         'url_params':{
              "platId": 1,
              "hashData": ""
          }
      }
    """
    * 接口返回码"200"
    * 验证接口返回值
    """
      {
            "status": 0,
            "msg": "返回数据成功",
            "info": [{
                "text": "挂件",
                "sub": [{
                    "text": "热门",
                    "sub": [{
                        "text": "观音",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/23.jpg",
                        "type": "catid",
                        "value": "23"
                    }, {
                        "text": "玉佛",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/24.jpg",
                        "type": "catid",
                        "value": "24"
                    }, {
                        "text": "貔貅",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/25.jpg",
                        "type": "catid",
                        "value": "25"
                    }, {
                        "text": "如意",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/26.jpg",
                        "type": "catid",
                        "value": "26"
                    }, {
                        "text": "福瓜",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/27.jpg",
                        "type": "catid",
                        "value": "27"
                    }, {
                        "text": "平安扣",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/28.jpg",
                        "type": "catid",
                        "value": "28"
                    }, {
                        "text": "叶子",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/29.jpg",
                        "type": "catid",
                        "value": "29"
                    }, {
                        "text": "财豆",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/30.jpg",
                        "type": "catid",
                        "value": "30"
                    }, {
                        "text": "路路通",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/31.jpg",
                        "type": "catid",
                        "value": "31"
                    }]
                }, {
                    "text": "其它挂件",
                    "sub": [{
                        "text": "玉白菜",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/32.jpg",
                        "type": "catid",
                        "value": "32"
                    }, {
                        "text": "葫芦",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/33.jpg",
                        "type": "catid",
                        "value": "33"
                    }, {
                        "text": "麒麟",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/34.jpg",
                        "type": "catid",
                        "value": "34"
                    }, {
                        "text": "关公",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/35.jpg",
                        "type": "catid",
                        "value": "35"
                    }, {
                        "text": "生肖",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/36.jpg",
                        "type": "catid",
                        "value": "36"
                    }, {
                        "text": "龙凤牌",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/39.jpg",
                        "type": "catid",
                        "value": "39"
                    }, {
                        "text": "瑞兽",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/40.jpg",
                        "type": "catid",
                        "value": "40"
                    }, {
                        "text": "人物",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/41.jpg",
                        "type": "catid",
                        "value": "41"
                    }, {
                        "text": "方牌",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/42.jpg",
                        "type": "catid",
                        "value": "42"
                    }, {
                        "text": "佛手",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/43.jpg",
                        "type": "catid",
                        "value": "43"
                    }, {
                        "text": "节节高",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/44.jpg",
                        "type": "catid",
                        "value": "44"
                    }, {
                        "text": "金蝉",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/45.jpg",
                        "type": "catid",
                        "value": "45"
                    }, {
                        "text": "喜富贵",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/46.jpg",
                        "type": "catid",
                        "value": "46"
                    }, {
                        "text": "花鸟鱼",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/47.jpg",
                        "type": "catid",
                        "value": "47"
                    }, {
                        "text": "福禄寿",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/48.jpg",
                        "type": "catid",
                        "value": "48"
                    }, {
                        "text": "所有挂件",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/22.jpg",
                        "type": "catid",
                        "value": "22"
                    }]
                }]
            }, {
                "text": "手镯",
                "sub": [{
                    "text": "形状",
                    "sub": [{
                        "text": "圆条",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/49.jpg",
                        "type": "catid",
                        "value": "49"
                    }, {
                        "text": "贵妃",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/50.jpg",
                        "type": "catid",
                        "value": "50"
                    }, {
                        "text": "扁条",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/51.jpg",
                        "type": "catid",
                        "value": "51"
                    }, {
                        "text": "方条",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/52.jpg",
                        "type": "catid",
                        "value": "52"
                    }, {
                        "text": "个性",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/53.jpg",
                        "type": "catid",
                        "value": "53"
                    }, {
                        "text": "所有形状",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/19.jpg",
                        "type": "catid",
                        "value": "19"
                    }]
                }, {
                    "text": "尺寸",
                    "sub": [{
                        "text": "52≤",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/55.jpg",
                        "type": "catid",
                        "value": "55",
                        "checks": "1"
                    }, {
                        "text": "53mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/56.jpg",
                        "type": "catid",
                        "value": "56",
                        "checks": "1"
                    }, {
                        "text": "54mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/57.jpg",
                        "type": "catid",
                        "value": "57",
                        "checks": "1"
                    }, {
                        "text": "55mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/58.jpg",
                        "type": "catid",
                        "value": "58",
                        "checks": "1"
                    }, {
                        "text": "56mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/59.jpg",
                        "type": "catid",
                        "value": "59",
                        "checks": "1"
                    }, {
                        "text": "57mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/60.jpg",
                        "type": "catid",
                        "value": "60",
                        "checks": "1"
                    }, {
                        "text": "58mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/61.jpg",
                        "type": "catid",
                        "value": "61",
                        "checks": "1"
                    }, {
                        "text": "59mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/62.jpg",
                        "type": "catid",
                        "value": "62",
                        "checks": "1"
                    }, {
                        "text": "≥60",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/63.jpg",
                        "type": "catid",
                        "value": "63",
                        "checks": "1"
                    }, {
                        "text": "所有手镯",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/19.jpg",
                        "type": "catid",
                        "value": "19",
                        "checks": "1"
                    }]
                }]
            }, {
                "text": "手表",
                "sub": [{
                    "text": "手表款式",
                    "sub": [{
                        "text": "男表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/64.jpg",
                        "type": "catid",
                        "value": "64"
                    }, {
                        "text": "女表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/65.jpg",
                        "type": "catid",
                        "value": "65"
                    }, {
                        "text": "对表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/66.jpg",
                        "type": "catid",
                        "value": "66"
                    }, {
                        "text": "所有手表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/18.jpg",
                        "type": "catid",
                        "value": "18"
                    }]
                }]
            }, {
                "text": "饰品",
                "sub": [{
                    "text": "饰品",
                    "sub": [{
                        "text": "胸针",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/86.jpg",
                        "type": "catid",
                        "value": "86"
                    }, {
                        "text": "项坠",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/87.jpg",
                        "type": "catid",
                        "value": "87"
                    }, {
                        "text": "戒指",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/88.jpg",
                        "type": "catid",
                        "value": "88"
                    }, {
                        "text": "耳钉",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/89.jpg",
                        "type": "catid",
                        "value": "89"
                    }, {
                        "text": "耳坠",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/90.jpg",
                        "type": "catid",
                        "value": "90"
                    }, {
                        "text": "手链",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/91.jpg",
                        "type": "catid",
                        "value": "91"
                    }, {
                        "text": "项链",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/92.jpg",
                        "type": "catid",
                        "value": "92"
                    }, {
                        "text": "所有饰品",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/20.jpg",
                        "type": "catid",
                        "value": "20"
                    }]
                }]
            }, {
                "text": "蛋面祼石",
                "sub": [{
                    "text": "蛋面祼石",
                    "sub": [{
                        "text": "戒面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/100.jpg",
                        "type": "catid",
                        "value": "100"
                    }, {
                        "text": "胸坠面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/101.jpg",
                        "type": "catid",
                        "value": "101"
                    }, {
                        "text": "手链\/项链面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/102.jpg",
                        "type": "catid",
                        "value": "102"
                    }, {
                        "text": "耳钉\/耳坠面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/103.jpg",
                        "type": "catid",
                        "value": "103"
                    }, {
                        "text": "查看所有",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/99.jpg",
                        "type": "catid",
                        "value": "99"
                    }]
                }]
            }, {
                "text": "杂项",
                "sub": [{
                    "text": "翡翠杂项",
                    "sub": [{
                        "text": "把玩",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/71.jpg",
                        "type": "catid",
                        "value": "71"
                    }, {
                        "text": "摆件",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/72.jpg",
                        "type": "catid",
                        "value": "72"
                    }, {
                        "text": "巧雕",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/98.jpg",
                        "type": "catid",
                        "value": "98"
                    }, {
                        "text": "印章",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/73.jpg",
                        "type": "catid",
                        "value": "73"
                    }, {
                        "text": "车包挂",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/74.jpg",
                        "type": "catid",
                        "value": "74"
                    }, {
                        "text": "其它",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/75.jpg",
                        "type": "catid",
                        "value": "75"
                    }, {
                        "text": "查看所有",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/21.jpg",
                        "type": "catid",
                        "value": "21"
                    }]
                }]
            }],
            "hashData": "",
            "cacheType": "none",
            "code": 0,
            "message": "返回数据成功",
            "data": [{
                "text": "挂件",
                "sub": [{
                    "text": "热门",
                    "sub": [{
                        "text": "观音",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/23.jpg",
                        "type": "catid",
                        "value": "23"
                    }, {
                        "text": "玉佛",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/24.jpg",
                        "type": "catid",
                        "value": "24"
                    }, {
                        "text": "貔貅",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/25.jpg",
                        "type": "catid",
                        "value": "25"
                    }, {
                        "text": "如意",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/26.jpg",
                        "type": "catid",
                        "value": "26"
                    }, {
                        "text": "福瓜",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/27.jpg",
                        "type": "catid",
                        "value": "27"
                    }, {
                        "text": "平安扣",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/28.jpg",
                        "type": "catid",
                        "value": "28"
                    }, {
                        "text": "叶子",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/29.jpg",
                        "type": "catid",
                        "value": "29"
                    }, {
                        "text": "财豆",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/30.jpg",
                        "type": "catid",
                        "value": "30"
                    }, {
                        "text": "路路通",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/31.jpg",
                        "type": "catid",
                        "value": "31"
                    }]
                }, {
                    "text": "其它挂件",
                    "sub": [{
                        "text": "玉白菜",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/32.jpg",
                        "type": "catid",
                        "value": "32"
                    }, {
                        "text": "葫芦",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/33.jpg",
                        "type": "catid",
                        "value": "33"
                    }, {
                        "text": "麒麟",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/34.jpg",
                        "type": "catid",
                        "value": "34"
                    }, {
                        "text": "关公",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/35.jpg",
                        "type": "catid",
                        "value": "35"
                    }, {
                        "text": "生肖",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/36.jpg",
                        "type": "catid",
                        "value": "36"
                    }, {
                        "text": "龙凤牌",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/39.jpg",
                        "type": "catid",
                        "value": "39"
                    }, {
                        "text": "瑞兽",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/40.jpg",
                        "type": "catid",
                        "value": "40"
                    }, {
                        "text": "人物",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/41.jpg",
                        "type": "catid",
                        "value": "41"
                    }, {
                        "text": "方牌",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/42.jpg",
                        "type": "catid",
                        "value": "42"
                    }, {
                        "text": "佛手",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/43.jpg",
                        "type": "catid",
                        "value": "43"
                    }, {
                        "text": "节节高",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/44.jpg",
                        "type": "catid",
                        "value": "44"
                    }, {
                        "text": "金蝉",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/45.jpg",
                        "type": "catid",
                        "value": "45"
                    }, {
                        "text": "喜富贵",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/46.jpg",
                        "type": "catid",
                        "value": "46"
                    }, {
                        "text": "花鸟鱼",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/47.jpg",
                        "type": "catid",
                        "value": "47"
                    }, {
                        "text": "福禄寿",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/48.jpg",
                        "type": "catid",
                        "value": "48"
                    }, {
                        "text": "所有挂件",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/22.jpg",
                        "type": "catid",
                        "value": "22"
                    }]
                }]
            }, {
                "text": "手镯",
                "sub": [{
                    "text": "形状",
                    "sub": [{
                        "text": "圆条",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/49.jpg",
                        "type": "catid",
                        "value": "49"
                    }, {
                        "text": "贵妃",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/50.jpg",
                        "type": "catid",
                        "value": "50"
                    }, {
                        "text": "扁条",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/51.jpg",
                        "type": "catid",
                        "value": "51"
                    }, {
                        "text": "方条",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/52.jpg",
                        "type": "catid",
                        "value": "52"
                    }, {
                        "text": "个性",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/53.jpg",
                        "type": "catid",
                        "value": "53"
                    }, {
                        "text": "所有形状",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/19.jpg",
                        "type": "catid",
                        "value": "19"
                    }]
                }, {
                    "text": "尺寸",
                    "sub": [{
                        "text": "52≤",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/55.jpg",
                        "type": "catid",
                        "value": "55",
                        "checks": "1"
                    }, {
                        "text": "53mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/56.jpg",
                        "type": "catid",
                        "value": "56",
                        "checks": "1"
                    }, {
                        "text": "54mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/57.jpg",
                        "type": "catid",
                        "value": "57",
                        "checks": "1"
                    }, {
                        "text": "55mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/58.jpg",
                        "type": "catid",
                        "value": "58",
                        "checks": "1"
                    }, {
                        "text": "56mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/59.jpg",
                        "type": "catid",
                        "value": "59",
                        "checks": "1"
                    }, {
                        "text": "57mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/60.jpg",
                        "type": "catid",
                        "value": "60",
                        "checks": "1"
                    }, {
                        "text": "58mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/61.jpg",
                        "type": "catid",
                        "value": "61",
                        "checks": "1"
                    }, {
                        "text": "59mm",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/62.jpg",
                        "type": "catid",
                        "value": "62",
                        "checks": "1"
                    }, {
                        "text": "≥60",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/63.jpg",
                        "type": "catid",
                        "value": "63",
                        "checks": "1"
                    }, {
                        "text": "所有手镯",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/19.jpg",
                        "type": "catid",
                        "value": "19",
                        "checks": "1"
                    }]
                }]
            }, {
                "text": "手表",
                "sub": [{
                    "text": "手表款式",
                    "sub": [{
                        "text": "男表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/64.jpg",
                        "type": "catid",
                        "value": "64"
                    }, {
                        "text": "女表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/65.jpg",
                        "type": "catid",
                        "value": "65"
                    }, {
                        "text": "对表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/66.jpg",
                        "type": "catid",
                        "value": "66"
                    }, {
                        "text": "所有手表",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/18.jpg",
                        "type": "catid",
                        "value": "18"
                    }]
                }]
            }, {
                "text": "饰品",
                "sub": [{
                    "text": "饰品",
                    "sub": [{
                        "text": "胸针",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/86.jpg",
                        "type": "catid",
                        "value": "86"
                    }, {
                        "text": "项坠",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/87.jpg",
                        "type": "catid",
                        "value": "87"
                    }, {
                        "text": "戒指",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/88.jpg",
                        "type": "catid",
                        "value": "88"
                    }, {
                        "text": "耳钉",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/89.jpg",
                        "type": "catid",
                        "value": "89"
                    }, {
                        "text": "耳坠",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/90.jpg",
                        "type": "catid",
                        "value": "90"
                    }, {
                        "text": "手链",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/91.jpg",
                        "type": "catid",
                        "value": "91"
                    }, {
                        "text": "项链",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/92.jpg",
                        "type": "catid",
                        "value": "92"
                    }, {
                        "text": "所有饰品",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/20.jpg",
                        "type": "catid",
                        "value": "20"
                    }]
                }]
            }, {
                "text": "蛋面祼石",
                "sub": [{
                    "text": "蛋面祼石",
                    "sub": [{
                        "text": "戒面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/100.jpg",
                        "type": "catid",
                        "value": "100"
                    }, {
                        "text": "胸坠面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/101.jpg",
                        "type": "catid",
                        "value": "101"
                    }, {
                        "text": "手链\/项链面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/102.jpg",
                        "type": "catid",
                        "value": "102"
                    }, {
                        "text": "耳钉\/耳坠面",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/103.jpg",
                        "type": "catid",
                        "value": "103"
                    }, {
                        "text": "查看所有",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/99.jpg",
                        "type": "catid",
                        "value": "99"
                    }]
                }]
            }, {
                "text": "杂项",
                "sub": [{
                    "text": "翡翠杂项",
                    "sub": [{
                        "text": "把玩",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/71.jpg",
                        "type": "catid",
                        "value": "71"
                    }, {
                        "text": "摆件",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/72.jpg",
                        "type": "catid",
                        "value": "72"
                    }, {
                        "text": "巧雕",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/98.jpg",
                        "type": "catid",
                        "value": "98"
                    }, {
                        "text": "印章",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/73.jpg",
                        "type": "catid",
                        "value": "73"
                    }, {
                        "text": "车包挂",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/74.jpg",
                        "type": "catid",
                        "value": "74"
                    }, {
                        "text": "其它",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/75.jpg",
                        "type": "catid",
                        "value": "75"
                    }, {
                        "text": "查看所有",
                        "logo": "https:\/\/appres.jaadee.com\/apps\/icon\/jaadee\/21.jpg",
                        "type": "catid",
                        "value": "21"
                    }]
                }]
            }]
        }
    """